name: Main CI Workflow

on: push

env:
  REPO_NAME: magda-auth-discourse-connect
  # Github account username (used for access github registry)
  GH_USERNAME: magdabot
  # Github Orgnisation name or user name for this repo
  GH_ORGNAME: magda-io


jobs:
  build-test-docker:
    name: Build, Test & Push to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: helm dep up deploy/${REPO_NAME}

      - run: yarn helm-lint

      - name: Login to GitHub Package Repository
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GH_USERNAME} -p ${GH_TOKEN}
      - name: Build Docker Image & Push
        run: yarn docker-build-prod --repository=docker.pkg.github.com/${GH_ORGNAME}/${REPO_NAME} --name=${REPO_NAME} --version=${GITHUB_SHA}

